# Log Application
logging:
  file: spring-logs/appiptu.log

spring:
  # Datasource List
  datasource:
    continue-on-error: true
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    password: appiptu
    platform: postgres
    url: jdbc:postgresql://dbdesk.ci347vo4wg5v.us-east-2.rds.amazonaws.com:5432/appiptu
    username: appiptu
    
  # Domain Identification
  jmx:
    default-domain: appiptu
  # JPA List
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
  # Path for Views MVC
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  # Ansi Output for Console
  output:
    ansi:
      enabled: always
